#+AUTHOR: Ashwin Godbole
#+OPTIONS: ^:{}

* CGSIMRD
** About
CGSIMRD, or /Coarse Grained Simulation of RNA and DNA/, is a software package that aids in performing coarse grain simulations of RNA and DNA using LAMMPS.

** Disclaimer
This project is under active development.

** Dependencies
The project depends on the following software packages
+ LAMMPS^{2} ([[https://www.lammps.org/][website]])
+ tacoxDNA^{1} ([[http://tacoxdna.sissa.it/][website]])
+ VMD^{2} ([[https://www.ks.uiuc.edu/Research/vmd/][website]])
+ Curl^{2} ([[https://curl.se/][website]])

_^{1} cgsimrd ships with *tacoxDNA*.
_^{2} cgsimrd *does not* ship with this.

(Regarding VMD, users may use any visualization software (eg: pymol). I use VMD and therefore have listed that as a dependency.)

** Directory structure
As of now, the project requires the following project structure.
#+begin_src
   .
   ├── inp [ generated lammps input scripts ]
   ├── lib [ tacoxDNA ]
   ├── lmp [ generated lammps data files (by tacoxDNA) ]
   ├── pdb [ downloaded pdb files ]
   ├── sim [ generated trajectory, energy data files ]
   └── src [ all the source scripts ]
#+end_src

** Directories
The source directory contains the following files :
#+begin_src
  src/
   ├── cleaner.sh       --> deletes pdb or lammps data files
   ├── getpdb.sh        --> script to download pdb files
   ├── makeinput.sh     --> generates input file from template
   ├── pdb2lmp.sh       --> converts pdbs to lammps data files using tacoxDNA
   ├── setup.sh         --> creates the directories that don't 
   ├── simulate.sh      --> performs simulation using input files and lammps
   ├── tmpl_dna.in      --> template input file for DNA pdbs
   ├── tmpl_rna.in      --> template input file for RNA pdbs
   └── visualize.sh     --> visualizes trajectory file using vmd
#+end_src

** Generated 'Output' Files
Every simulation produces a certain number of files with data regarding the trajectory of particles or their energy at certain time-steps during the simulations. These files are then used later for further analysis and for visualizaing the simulation.

Since those files contain only the data and no instructions regarding how the data in those files is to be interpretted, I'm putting that information here.

| File extension | Description                                                     |
|----------------+-----------------------------------------------------------------|
| xyz            | contains data required by visualization software                |
| energy         | contains energy data, can be used by other scripts for analysis |
