#+AUTHOR: Ashwin Godbole
#+OPTIONS: ^:{}

* CGSIMRD
** About
CGSIMRD, or /Coarse Grained Simulation of RNA and DNA/, is a software package that aids in performing coarse grain simulations of RNA and DNA using LAMMPS.

** Disclaimer
This project is under active development. Stuff *will* break from time to time.

** Dependencies
The project depends on the following software packages
+ LAMMPS^{2} ([[https://www.lammps.org/][website]])
+ tacoxDNA^{1} ([[http://tacoxdna.sissa.it/][website]])
+ oxview^{2} ([[https://github.com/sulcgroup/oxdna-viewer][website]])
+ Curl^{2} ([[https://curl.se/][website]])

1 : cgsimrd ships with *tacoxDNA*.

2 : cgsimrd *does not* ship with LAMMPS, oxview or Curl.

** Simulation Process
The simulation process has many steps. These are :
+ download the necessary pdb file
+ convert the pdb file into oxDNA config and topology files
+ convert the oxDNA files to a LAMMPS data file
+ generate an input script for LAMMPS
+ perform the simulation
+ convert the trajectory file into oxDNA config and topology files
+ visualize the oxDNA files using oxview

** Root Directory Structure
As of now, the project requires the following project structure.
#+begin_src
   .
   ├── inp         [ generated lammps input scripts ]
   ├── lib         [ tacoxDNA ]
   ├── lmp         [ generated lammps data files (by tacoxDNA) ]
   ├── pdb         [ downloaded pdb files ]
   ├── sim         [ generated trajectory, energy data files ]
   ├── oxdna_files [ store the oxdna config and topology files for visualizations ]
   └── src         [ all the source scripts ]
#+end_src

** Directories
The source directory contains the following files :
#+begin_src
  src/
   ├── cleaner.sh       --> deletes pdb or lammps data files
   ├── getpdb.sh        --> script to download pdb files
   ├── makeinput.sh     --> generates input file from template
   ├── pdb2lmp.sh       --> converts pdbs to lammps data files using tacoxDNA
   ├── setup.sh         --> creates the directories that don't 
   ├── simulate.sh      --> performs simulation using input files and lammps
   ├── tmpl_dna.in      --> template input file for DNA pdbs
   ├── tmpl_rna.in      --> template input file for RNA pdbs
   └── visualize.sh     --> visualizes trajectory file using oxview
#+end_src

** Usage
Currently, the path to the lammps executable is set to a hardcoded path on my system. You'll need to change that in `src/simulate.sh` to be able to run the script.
